import streamlit as st
import time

# --- Page Config ---
st.set_page_config(page_title="AquaLogic | AI Policy Navigator", page_icon="💧", layout="wide")

# --- Custom CSS for "Premium" Look ---
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stButton>button { width: 100%; border-radius: 5px; height: 3em; background-color: #0041d3; color: white; }
    .stExpander { background-color: white; border-radius: 10px; border: 1px solid #e6e9ef; }
    </style>
    """, unsafe_allow_html=True)

# --- Sidebar (Professional Navigation) ---
with st.sidebar:
    st.image("https://img.icons8.com/fluency/96/water.png", width=80)
    st.title("AquaLogic Control")
    st.info("Powered by IBM Granite-13B")
    st.divider()
    st.subheader("Project Evidence")
    st.success("✅ .bob Metadata Detected")
    st.success("✅ SDG 6 Aligned")
    st.divider()
    st.caption("1M1B AI for Sustainability Internship")

# --- Main Dashboard ---
st.title("💧 AquaLogic: Water Policy & Action Navigator")
st.markdown("##### *Empowering Citizens through AI-Driven Legal Clarity*")

col1, col2 = st.columns([2, 1])

with col1:
    st.markdown("### 🔍 Policy Inquiry")
    query = st.text_input("What would you like to clarify today?", placeholder="e.g. Can I use a hose to wash my car during a Level 2 alert?")
    
    feature = st.selectbox("Choose Service Mode", 
                          ["Jargon-to-Action Translator", "Policy Comparison Agent", "Conservation Checklist Generator"])

    if st.button("Generate Grounded Analysis"):
        with st.status("Initializing RAG Pipeline...", expanded=True) as status:
            st.write("Retrieving municipal documents...")
            time.sleep(1)
            st.write("Grounding in IBM Granite-13B logic...")
            time.sleep(1)
            status.update(label="Analysis Complete!", state="complete", expanded=False)

        # --- Professional Response Area ---
        st.markdown("---")
        st.markdown("### 📝 AI Consultant Response")
        
        # This is where your logic from run_diagnostic would display
        st.success("**Grounded Answer:** Under Section 16.8 of the Summer Protocols, using a pressurized hose for car washing is strictly prohibited between 08:00 and 18:00 during Level 2 alerts.")
        
        with st.expander("📄 View Source Evidence (Anti-Hallucination)"):
            st.code("[Source: Municipal Water Bylaw 2023, Section 16.8, Page 14]\n'Utilization of pressurized hosepipes... is strictly prohibited... Citizens mandated to use bucket-and-sponge.'", language="text")

with col2:
    st.markdown("### 📈 Impact Metrics")
    st.metric(label="Potential Water Saving", value="30 Liters/Day", delta="Sustainability Gain")
    st.metric(label="Compliance Probability", value="98%", delta="High Accuracy")
    
    st.markdown("---")
    st.markdown("### ✅ Action Plan")
    check1 = st.checkbox("Switch to bucket-and-sponge method")
    check2 = st.checkbox("Apply for Class-B Usage Permit")
    
    # --- Professional Download Logic ---
    # We create the text content for the file here
    action_plan_text = f"""
    AQUALOGIC ACTION PLAN
    ---------------------
    Status: Generated by IBM Granite RAG
    
    1. Action: { 'COMPLETED' if check1 else 'PENDING' } - Switch to bucket-and-sponge method.
    2. Action: { 'COMPLETED' if check2 else 'PENDING' } - Apply for Class-B Usage Permit.
    
    Grounding: Based on Municipal Water Bylaw 2023.
    """
    
    st.download_button(
        label="📥 Download Action Plan (Text)",
        data=action_plan_text,
        file_name="AquaLogic_Action_Plan.txt",
        mime="text/plain"
    )
st.divider()
st.caption("Responsible AI Statement: This assistant is grounded in specific municipal datasets. It will not generate legal advice outside of provided document contexts.")